codecov:
    notify:
        # do not notify until at least 16 builds (python versions * os * extension = 4 * 3 * 2 = 24) have been uploaded from the CI pipeline
        after_n_builds: 24 # https://docs.codecov.com/docs/codecovyml-reference#codecovnotify
coverage:
  status:
    project:
      default:
        target: auto # https://docs.codecov.com/docs/commit-status#target
        # test coverage may change a bit depending on the computer executed
        threshold: 1% # https://docs.codecov.com/docs/commit-status#threshold