codecov:
    notify:
        # do not notify until at least 16 builds (python versions * os * extension = 5 * 2 * 2 = 20) have been uploaded from the CI pipeline
        after_n_builds: 20 # https://docs.codecov.com/docs/codecovyml-reference#codecovnotify
coverage:
  status:
    project:
      default:
        target: auto # https://docs.codecov.com/docs/commit-status#target
        # test coverage may change a bit depending on the computer executed
        threshold: 2% # https://docs.codecov.com/docs/commit-status#threshold