from lxml import etree

parser = etree.ETCompatXMLParser(resolve_entities=False)

qn_complex_type = etree.QName('http://www.w3.org/2001/XMLSchema', 'complexType')
qn_element = etree.QName('http://www.w3.org/2001/XMLSchema', 'element')


def _generate_qnames(element, names, target_namespace):
    tag = etree.QName(element.tag)
    if tag == qn_complex_type:
        name = element.attrib.get('name')
        if name:
            names[name] = etree.QName(target_namespace, name)
    elif tag == qn_element:
        name = element.attrib.get('name')
        if name:
            names[name] = etree.QName(target_namespace, name)
    for child in element:
        _generate_qnames(child, names, target_namespace)


def generate_qnames(doc):
    names = {}
    target_namespace = doc.attrib['targetNamespace']
    _generate_qnames(doc, names, target_namespace)
    return names


def write_names_file(names, ns_helper, ns_name, fd):
    fd.write('# generated by "generate_qnames"\n')
    fd.write(f'from ..namespaces import {ns_helper}\n\n')
    fd.write('')
    names_list = [n.localname for n in names.values()]
    names_list.sort()
    for name in names_list:
        fd.write(f"{name} = {ns_helper}.{ns_name}.tag('{name}')\n")


if __name__ == '__main__':
    with open('../src/sdc11073/xsd/BICEPS_ParticipantModel.xsd', 'rb') as pm:
        xml_string = pm.read()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with open('../src/sdc11073/xml_types/pm_qnames.py', 'w') as stream:
        write_names_file(qnames, 'default_ns_helper', 'PM', stream)

    with open('../src/sdc11073/xsd/BICEPS_MessageModel.xsd', 'rb') as pm:
        xml_string = pm.read()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with open('../src/sdc11073/xml_types/msg_qnames.py', 'w') as stream:
        write_names_file(qnames, 'default_ns_helper', 'MSG', stream)

    with open('../src/sdc11073/xsd/Extensionpoint.xsd', 'rb') as pm:
        xml_string = pm.read()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with open('../src/sdc11073/xml_types/ext_qnames.py', 'w') as stream:
        write_names_file(qnames, 'default_ns_helper', 'EXT', stream)
