"""The module generates the qnames modules of the xml_types package from the BICEPS schema files."""

# ruff: noqa: INP001  this is a standalone script, not part of a package

import pathlib
from typing import TextIO, TypeAlias

from lxml import etree

LxmlElement: TypeAlias = etree._Element  # noqa: SLF001

parser = etree.ETCompatXMLParser(resolve_entities=False)

qn_complex_type = etree.QName('http://www.w3.org/2001/XMLSchema', 'complexType')
qn_element = etree.QName('http://www.w3.org/2001/XMLSchema', 'element')


def _generate_qnames(element: LxmlElement, names: dict[str, etree.QName], target_namespace: str) -> None:
    tag = etree.QName(element.tag)
    if tag in (qn_complex_type, qn_element):
        name = element.attrib.get('name')
        if name:
            names[name] = etree.QName(target_namespace, name)
    for child in element:
        _generate_qnames(child, names, target_namespace)


def generate_qnames(doc: LxmlElement) -> dict[str, etree.QName]:
    """Collect the QNames of all named complexType and element definitions of a schema document."""
    names: dict[str, etree.QName] = {}
    target_namespace = doc.attrib['targetNamespace']
    _generate_qnames(doc, names, target_namespace)
    return names


def write_names_file(names: dict[str, etree.QName], ns_helper: str, ns_name: str, fd: TextIO, docstring: str) -> None:
    """Write a qnames module for the provided QNames to the already opened file fd."""
    fd.write(f'"""{docstring}"""\n\n')
    fd.write('# generated by "generate_qnames"\n')
    fd.write(f'from ..namespaces import {ns_helper}\n\n')
    fd.write('')
    names_list = [n.localname for n in names.values()]
    names_list.sort()
    fd.writelines(f"{name} = {ns_helper}.{ns_name}.tag('{name}')\n" for name in names_list)


if __name__ == '__main__':
    xml_string = pathlib.Path('../src/sdc11073/xsd/BICEPS_ParticipantModel.xsd').read_bytes()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with pathlib.Path('../src/sdc11073/xml_types/pm_qnames.py').open('w') as stream:
        write_names_file(
            qnames,
            'default_ns_helper',
            'PM',
            stream,
            'The module contains the QNames of the BICEPS ParticipantModel.',
        )

    xml_string = pathlib.Path('../src/sdc11073/xsd/BICEPS_MessageModel.xsd').read_bytes()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with pathlib.Path('../src/sdc11073/xml_types/msg_qnames.py').open('w') as stream:
        write_names_file(
            qnames,
            'default_ns_helper',
            'MSG',
            stream,
            'The module contains the QNames of the BICEPS MessageModel.',
        )

    xml_string = pathlib.Path('../src/sdc11073/xsd/Extensionpoint.xsd').read_bytes()
    doc_root = etree.fromstring(xml_string, parser=parser)
    qnames = generate_qnames(doc_root)
    with pathlib.Path('../src/sdc11073/xml_types/ext_qnames.py').open('w') as stream:
        write_names_file(
            qnames,
            'default_ns_helper',
            'EXT',
            stream,
            'The module contains the QNames of the BICEPS ExtensionPoint.',
        )
