name: Build package

on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - master
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@v47
        with:
          files: '**.py'

      - name: ruff check
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
          src: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: ruff format check
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
          args: "format --check --diff"
          src: ${{ steps.changed-files.outputs.all_changed_files }}

  build:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      WHL: ${{ steps.filenames.outputs.WHL }}
      TARGZ: ${{ steps.filenames.outputs.TARGZ }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set new version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          uv version ${GITHUB_REF/refs\/tags\/v/}

      - name: Build package
        run: uv build

      - name: Set filenames in output
        id: filenames
        run: |
          echo WHL=$(echo dist/*.whl) >> $GITHUB_OUTPUT
          echo TARGZ=$(echo dist/*.tar.gz) >> $GITHUB_OUTPUT
      - name: Archive package
        uses: actions/upload-artifact@v7
        with:
          name: distributions
          path: dist
          retention-days: 5

  tests:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ ubuntu-latest, windows-latest ]
        distribution: [ "${{ needs.build.outputs.WHL }}",
                        "${{ needs.build.outputs.TARGZ }}" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache-suffix: ${{ matrix.distribution }}

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: distributions
          path: dist

      - name: Install dependencies
        run: uv sync --group test

      - name: Install package
        run: uv pip install ${{ matrix.distribution }}

      - name: Detect suffix on ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo SUFFIX=$(python -c "import pathlib;p=pathlib.Path('${{ matrix.distribution }}');print('whl') if p.suffix=='.whl' else print('tar_gz')") >> $GITHUB_ENV

      - name: Detect suffix on windows
        if: ${{ matrix.os == 'windows-latest' }}
        # https://github.com/actions/runner-images/issues/5251#issuecomment-1071030822
        run: |
          echo SUFFIX=$(python -c "import pathlib;p=pathlib.Path('${{ matrix.distribution }}');print('whl') if p.suffix=='.whl' else print('tar_gz')") | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run pytest
        run: >-
          uv run --no-sync pytest
          --html=pytest_reports/unittest_report_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.html
          --self-contained-html
          --cov=$(uv run --no-sync python -c "import pathlib;import sdc11073;print(pathlib.Path(sdc11073.__file__).parent)")
          --cov-report=xml
          --log-file pytest_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.log

      - name: Save venv setup
        run: uv export > pytest_reports/unittest_report_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}_requirements.txt

      - name: Archive test result
        uses: actions/upload-artifact@v7
        if: success() || failure()  # upload artifacts also if test stage failed
        with:
          name: unittest_reports-${{ matrix.os }}-py${{ matrix.python-version }}-${{ env.SUFFIX }}
          path: pytest_reports/unittest_report_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}*
          retention-days: 5

      - name: Archive test log
        uses: actions/upload-artifact@v7
        if: success() || failure()  # upload artifacts also if test stage failed
        with:
          name: pytest_logs-${{ matrix.os }}-py${{ matrix.python-version }}-${{ env.SUFFIX }}
          path: pytest_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.log
          retention-days: 5



      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
